version: "3.5"
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: nginx:inception
    container_name: nginx
    ports:
      - 443:443