version: "3.5"


services:
#########################
########  Nginx  ########
#########################
  nginx:
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    image: nginx:inception
    container_name: nginx
    extra_hosts: 
      - ${LOGIN}.42.fr:127.0.0.1
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/wordpress

##########################
######  Wordpress  #######
##########################
  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    image: wordpress:inception
    container_name: wordpress
    environment:
      LOGIN: ${LOGIN}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    restart: always
    expose: 
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/wordpress

#########################
#######  MariaDB  #######
#########################
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        MARIADB_VERSION: ${MARIADB_VERSION}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ADMIN: ${MYSQL_ADMIN}
        MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
    image: mariadb:inception
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - wordpress_database:/var/lib/mysql

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_files:
    name: wordpress_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress_files
  wordpress_database:
    name: wordpress_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress_database
