version: "3.7"
services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    image: nginx:inception
    container_name: nginx
    ports:
      - 80:80
      - 443:443