version: "3.5"

services:

  nginx:
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    environment: 
      LOGIN: ${LOGIN}
    image: nginx:inception
    container_name: nginx
    ports:
      - "443:443"
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/wordpress
  
  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
    image: wordpress:inception
    container_name: wordpress
    expose: 
      - "9000"
      - "3306"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/wordpress

  mariadb:
    #build:
    #  context: requirements/mariadb
    #  dockerfile: Dockerfile
    #  args:
    #   ALPINE_VERSION: ${ALPINE_VERSION}
    #    MARIADB_VERSION: ${MARIADB_VERSION}
    image: mariadb:10.6
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - wordpress_database:/var/lib/mysql

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_files:
    name: wordpress_files
  wordpress_database:
    name: wordpress_database
  #  driver: local
  #  driver_opts:
  #    type: none
  #    o: bind
  #    device: /home/${LOGIN}/data
