version: "3.7"
services:
  nginx:
    build: #requirements/nginx/Dockerfile
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    container_name: nginx
    ports:
      - 443:443